# Computational thinking {#Motivation}

## Why computational thinking 

> If social scientists want to know how to work smart and not just hard, they need to take full advantage of the power of modern programming languages, and that power is automation. - [Jae Yeon Kim](https://dlab.berkeley.edu/blog/why-teaching-social-scientists-how-code-professional-important)

## Computational way of thinking about data 

### Structure 
- Structured data (Excel spreadsheets, CSVs)
  - Tidy data 
- Semi-structured data 
  - HTML/CSS: Websites 
  - JSON/XML: APIs

### Dimensions 
- Low-dimensional data (n > p)
- High-dimensional data (n < p)

## Computational way of thinking about research process

- Computational tools and techniques make doing traditional research easier, faster, scalable, and more reproducible
  - Data wrangling 
  - Modeling 
  - Visualization 
- Computational tools and techniques make documentation and collaboration easier, faster, scalable and safer
  - Dynamic reporting (markdown)
  - Version control system (Git and GitHub)
- Computational tools and techniques make collecting and analyzing large and complex data possible 
  - Digital data collection (API and web scraping)
      - Building a data infrastructure (SQL)
  - Machine learning 
